name: Check Commit Messages
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check source branch name
        run: |
          SOURCE_BRANCH=$(git branch --show-current)
          echo "Source branch: $SOURCE_BRANCH"
          if [[ "$SOURCE_BRANCH" != "AC-1234" ]]; then
            echo "Cannot merge. Source branch is not AC-1234."
            exit 1
          fi
