name: Check PR Source Branch
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-pr-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read allowed branches from file
        run: |
          mapfile -t ALLOWED_BRANCHES < .github/workflows/allowed_branches.txt
          echo "ALLOWED_BRANCHES=${ALLOWED_BRANCHES[*]}" >> $GITHUB_ENV

      - name: Extract branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Check if branch is allowed
        run: |
          BRANCH_NAME=${{ steps.branch-name.outputs.current_branch }}
          JIRA_NUM=$(echo "$BRANCH_NAME" | grep -oE '^AC-[0-9]{4}')
          echo "Source branch: $BRANCH_NAME"
          echo "Jira ticket: $JIRA_NUM"
          echo "Allowed branches: ${ALLOWED_BRANCHES[*]}"
          
          if [[ ! "${ALLOWED_BRANCHES[*]}" == "${JIRA_NUM}" ]]; then
            echo "The branch ${BRANCH_NAME} is NOT allowed for merging."
            exit 1
          else
            echo "The branch ${BRANCH_NAME} is allowed for merging."
          fi
