name: Check PR Source Branch
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Set branch name as environment variable
        run: |
          echo "BRANCH_NAME=${{ steps.branch-name.outputs.current_branch }}" >> $GITHUB_ENV

      - name: Print branch name
        run: |
          echo "Branch: $BRANCH_NAME"

      - name: Check if branch is AC-1234
        run: |
          if [[ "$BRANCH_NAME" != "AC-1234" ]]; then
            echo "The branch is not AC-1234."
            exit 1
          else
            echo "The branch is AC-1234."
          fi
