name: Check Commit Messages
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check commit messages
        run: |
          COMMIT_MSG=$(git log --format=%B -n 1 ${{ github.event.before }}..${{ github.sha }})
          echo "Commit message: $COMMIT_MSG"
          if [[ $COMMIT_MSG =~ ^AC-1234.* ]]; then
            echo "PR commit message starts with AC-1234."
          else
            echo "PR commit message must start with a matching pattern AC-1234."
            exit 1 
          fi
