name: Check PR Source Branch
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-pr-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read allowed branches from file
        run: |
          mapfile -t ALLOWED_BRANCHES < .github/workflows/allowed_branches.txt

      - name: Extract branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Set branch name as environment variable
        run: |
          BRANCH_NAME=${{ steps.branch-name.outputs.current_branch }}
          
          if [[ ! " ${ALLOWED_BRANCHES[*]} " =~ " ${BRANCH_NAME} " ]]; then
            echo "The branch is not allowed for merging."
            exit 1
          else
            echo "The branch is allowed for merging."
          fi
